# Generated by Django 5.1.2 on 2024-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationtask',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
