# Generated by Django 5.1.2 on 2024-11-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_correlationtask_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlecorrelation',
            name='correlation_task',
        ),
        migrations.AddField(
            model_name='singlecorrelation',
            name='correlation_tasks',
            field=models.ManyToManyField(related_name='single_correlations', to='core.correlationtask'),
        ),
    ]
