# Generated by Django 5.1.2 on 2024-11-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_singlecorrelation_correlation_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_tasks', to='core.task'),
        ),
    ]
