# Generated by Django 5.1.2 on 2024-11-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_correlationtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed')], default='in_progress', max_length=50),
        ),
        migrations.AddField(
            model_name='singlecorrelation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
