# Generated by Django 5.1.2 on 2024-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_correlationtask_status_singlecorrelation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationtask',
            name='capec_version',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='correlationtask',
            name='preprocessing_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
