# Generated by Django 5.1.2 on 2024-11-12 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_correlationtask_capec_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecorrelation',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_correlations', to='core.task'),
        ),
    ]
