# Generated by Django 5.1.2 on 2024-11-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_singlecorrelation_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlecorrelation',
            name='correlation_tasks',
        ),
        migrations.RemoveField(
            model_name='singlecorrelation',
            name='capec_ids',
        ),
        migrations.AddField(
            model_name='singlecorrelation',
            name='hosts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cve_hosts',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='CorrelationTask',
        ),
    ]
