# Generated by Django 5.1.2 on 2024-11-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_singlecorrelation_correlation_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.JSONField(help_text="Dizionario che associa CVE a una lista di CAPEC, es. {'CVE-XXX': ['CAPEC-1', 'CAPEC-2']}")),
            ],
        ),
    ]
