# Generated by Django 5.1.2 on 2024-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_groundtruth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('correlation', 'Correlation'), ('groundtruth', 'Groundtruth'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
