# Generated by Django 5.1.2 on 2024-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_models',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
