# Generated by Django 5.1.2 on 2024-11-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_update', models.DateTimeField(blank=True, null=True)),
                ('has_been_updated', models.BooleanField(default=False)),
                ('update_frequency', models.IntegerField(blank=True, help_text='Frequency of updates in days', null=True)),
            ],
        ),
    ]
