# Generated by Django 5.1.1 on 2024-11-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_add_initial_dataupdate_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capec_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CWE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('abstraction', models.CharField(choices=[('Pillar', 'Pillar'), ('Compound', 'Compound'), ('Base', 'Base'), ('Variant', 'Variant'), ('Class', 'Class')], max_length=50)),
                ('structure', models.CharField(choices=[('Simple', 'Simple'), ('Chain', 'Chain'), ('Composite', 'Composite')], max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Incomplete', 'Incomplete'), ('Stable', 'Stable'), ('Deprecated', 'Deprecated'), ('Obsolete', 'Obsolete'), ('Usable', 'Usable')], max_length=50)),
                ('description', models.TextField()),
                ('extended_description', models.TextField(blank=True, null=True)),
                ('likelihood_of_exploit', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('affected_resources', models.JSONField(blank=True, null=True)),
                ('alternate_terms', models.JSONField(blank=True, null=True)),
                ('applicable_platforms', models.JSONField(blank=True, null=True)),
                ('backgrouns_details', models.JSONField(blank=True, null=True)),
                ('common_consequences', models.JSONField(blank=True, null=True)),
                ('demonstrative_examples', models.JSONField(blank=True, null=True)),
                ('detection_methods', models.JSONField(blank=True, null=True)),
                ('functional_areas', models.JSONField(blank=True, null=True)),
                ('modes_of_introduction', models.JSONField(blank=True, null=True)),
                ('potential_mitigations', models.JSONField(blank=True, null=True)),
                ('observed_examples', models.JSONField(blank=True, null=True)),
                ('related_attack_patterns', models.ManyToManyField(blank=True, related_name='cwe_related_attack_patterns', to='data.capec')),
            ],
        ),
        migrations.CreateModel(
            name='CWERelatedWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('ChildOf', 'ChildOf'), ('ParentOf', 'ParentOf'), ('StartsWith', 'StartsWith'), ('CanFollow', 'CanFollow'), ('RequiredBy', 'RequiredBy'), ('Requires', 'Requires'), ('PeerOf', 'PeerOf'), ('CanPrecede', 'CanPrecede'), ('CanAlsoBe', 'CanAlsoBe')], max_length=50)),
                ('cwe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_weaknesses_from', to='data.cwe')),
                ('related_cwe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_weaknesses_to', to='data.cwe')),
            ],
        ),
        migrations.AddField(
            model_name='cwe',
            name='related_weaknesses',
            field=models.ManyToManyField(related_name='cwe_related_weaknesses', through='data.CWERelatedWeakness', to='data.cwe'),
        ),
    ]
