# Generated by Django 5.1.2 on 2024-11-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_capec_cwe_cwerelatedweakness_cwe_related_weaknesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cwe',
            old_name='backgrouns_details',
            new_name='background_details',
        ),
    ]
