# Generated by Django 5.1.2 on 2024-11-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_backgrouns_details_cwe_background_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capec',
            name='capec_id',
        ),
        migrations.AddField(
            model_name='capec',
            name='abstraction',
            field=models.CharField(choices=[('Meta', 'Meta'), ('Standard', 'Standard'), ('Detailed', 'Detailed')], default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='capec',
            name='alternate_terms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='consequences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='example_instances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='extended_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='indicators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='likelihood_of_attack',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='mitigations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='name',
            field=models.CharField(default='Generic Name', max_length=255),
        ),
        migrations.AddField(
            model_name='capec',
            name='prerequisites',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='related_cwe_weaknesses',
            field=models.ManyToManyField(blank=True, related_name='related_to_capecs', to='data.cwe'),
        ),
        migrations.AddField(
            model_name='capec',
            name='resources_required',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='skills_required',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='status',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Deprecated', 'Deprecated'), ('Draft', 'Draft'), ('Incomplete', 'Incomplete'), ('Obsolete', 'Obsolete'), ('Usable', 'Usable')], default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='capec',
            name='typical_severity',
            field=models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='capec',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='CAPECRelatedAttackPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('ChildOf', 'ChildOf'), ('ParentOf', 'ParentOf'), ('PeerOf', 'PeerOf'), ('CanAlsoBe', 'CanAlsoBe'), ('CanFollow', 'CanFollow'), ('CanPrecede', 'CanPrecede')], max_length=20)),
                ('source_capec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_related_patterns', to='data.capec')),
                ('target_capec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_related_patterns', to='data.capec')),
            ],
            options={
                'unique_together': {('source_capec', 'target_capec', 'nature')},
            },
        ),
        migrations.AddField(
            model_name='capec',
            name='related_patterns',
            field=models.ManyToManyField(blank=True, through='data.CAPECRelatedAttackPattern', to='data.capec'),
        ),
        migrations.CreateModel(
            name='ExecutionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_flow', to='data.capec')),
            ],
        ),
        migrations.AddField(
            model_name='capec',
            name='execution_flow_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_capec', to='data.executionflow'),
        ),
        migrations.CreateModel(
            name='AttackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
                ('phase', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('techniques', models.JSONField(blank=True, null=True)),
                ('execution_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_steps', to='data.executionflow')),
            ],
            options={
                'unique_together': {('execution_flow', 'step')},
            },
        ),
    ]
