# Generated by Django 5.1.2 on 2024-11-07 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_capec_capec_id_capec_abstraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('assigner', models.CharField(max_length=255)),
                ('data_type', models.CharField(blank=True, max_length=10, null=True)),
                ('data_format', models.CharField(blank=True, max_length=10, null=True)),
                ('data_version', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('impact_v2', models.JSONField(blank=True, null=True)),
                ('impact_v3', models.JSONField(blank=True, null=True)),
                ('vulnerable_cpe_uris', models.JSONField(blank=True, null=True)),
                ('related_cpe_uris', models.JSONField(blank=True, null=True)),
                ('related_cwes', models.ManyToManyField(blank=True, related_name='cve_related_weaknesses', to='data.cwe')),
            ],
        ),
        migrations.CreateModel(
            name='CVEReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('refsource', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='data.cve')),
            ],
        ),
    ]
