# Generated by Django 5.1.2 on 2024-11-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_cve_cvereference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='assigner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='data_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='data_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='data_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cvereference',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
