# Generated by Django 5.1.2 on 2024-11-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_cve_assigner_alter_cve_data_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='data_format',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='data_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='data_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cvereference',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvereference',
            name='refsource',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvereference',
            name='url',
            field=models.TextField(),
        ),
    ]
