# Generated by Django 5.1.2 on 2024-11-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_cve_data_format_alter_cve_data_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attackstep',
            unique_together=set(),
        ),
    ]
