# Generated by Django 5.1.2 on 2024-11-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_attackstep_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupdate',
            name='version',
            field=models.CharField(blank=True, help_text='Current version of the data entity', max_length=20, null=True),
        ),
    ]
