# Generated by Django 5.1.2 on 2024-11-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_dataupdate_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessedCAPEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capec_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(default='Generic Name', max_length=255)),
                ('preprocessed_version', models.CharField(default='v.1.0', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_aggregated', models.TextField(blank=True, null=True)),
                ('extended_description', models.TextField(blank=True, null=True)),
                ('extended_description_aggregated', models.TextField(blank=True, null=True)),
                ('indicators', models.JSONField(blank=True, null=True)),
                ('indicators_aggregated', models.TextField(blank=True, null=True)),
                ('prerequisites', models.JSONField(blank=True, null=True)),
                ('prerequisites_aggregated', models.TextField(blank=True, null=True)),
                ('resources_required', models.JSONField(blank=True, null=True)),
                ('resources_required_aggregated', models.TextField(blank=True, null=True)),
                ('mitigations', models.JSONField(blank=True, null=True)),
                ('mitigations_aggregated', models.TextField(blank=True, null=True)),
                ('example_instances', models.JSONField(blank=True, null=True)),
                ('example_instances_aggregated', models.TextField(blank=True, null=True)),
                ('consequences', models.JSONField(blank=True, null=True)),
                ('consequences_aggregated', models.TextField(blank=True, null=True)),
                ('skills_required', models.JSONField(blank=True, null=True)),
                ('skills_required_aggregated', models.TextField(blank=True, null=True)),
                ('alternate_terms', models.JSONField(blank=True, null=True)),
                ('alternate_terms_aggregated', models.TextField(blank=True, null=True)),
                ('overall_aggregated_text', models.TextField(blank=True, null=True)),
                ('original_capec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_version', to='data.capec')),
            ],
        ),
        migrations.CreateModel(
            name='PreprocessedExecutionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprocessed_capec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_flow', to='data.preprocessedcapec')),
            ],
        ),
        migrations.AddField(
            model_name='preprocessedcapec',
            name='preprocessed_execution_flow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_capec', to='data.preprocessedexecutionflow'),
        ),
        migrations.CreateModel(
            name='PreprocessedAttackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
                ('phase', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_aggregated', models.TextField(blank=True, null=True)),
                ('techniques', models.JSONField(blank=True, null=True)),
                ('techniques_aggregated', models.TextField(blank=True, null=True)),
                ('preprocessed_execution_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_attack_steps', to='data.preprocessedexecutionflow')),
            ],
        ),
    ]
