# Generated by Django 5.1.2 on 2024-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_preprocessedcapec_preprocessedexecutionflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessedcapec',
            name='capec_id',
        ),
        migrations.AlterField(
            model_name='preprocessedcapec',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
