# Generated by Django 5.1.2 on 2024-11-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_remove_preprocessedcapec_capec_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preprocessedcapec',
            unique_together={('original_capec', 'preprocessed_version')},
        ),
    ]
