# Generated by Django 5.1.2 on 2024-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_preprocessedcapec_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessedcapec',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
