# Generated by Django 5.1.2 on 2024-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_preprocessedcapec_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preprocessedcapec',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='preprocessedcapec',
            constraint=models.UniqueConstraint(fields=('original_capec', 'preprocessed_version'), name='unique_capec_version'),
        ),
    ]
