# Generated by Django 5.1.2 on 2024-11-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_preprocessedcapec_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessedcapec',
            name='original_capec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_versions', to='data.capec'),
        ),
    ]
