# Generated by Django 5.1.2 on 2024-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_preprocessedcapec_original_capec'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupdate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Failed', 'Failed')], default='Pending', help_text='Status of the update', max_length=20),
        ),
    ]
