# Generated by Django 5.1.2 on 2024-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_dataupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackstep',
            name='description_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attackstep',
            name='techniques_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='alternate_terms_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='consequences_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='description_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='example_instances_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='extended_description_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='indicators_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='mitigations_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='overall_aggregated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='prerequisites_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='resources_required_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capec',
            name='skills_required_aggregated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
